name: flutter_callkit
description: Flutter Callkit Incoming to show callkit screen in your Flutter app.
version: 2.0.4
homepage: https://github.com/suhailzoft/flutter_callkit
repository: https://github.com/suhailzoft/flutter_callkit
issue_tracker: https://github.com/suhailzoft/flutter_callkit/issues


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.20.0"


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  shared_preferences: 2.0.7

flutter:

  plugin:
    platforms:
      android:
        package: com.bayshore.flutter_callkit
        pluginClass: FlutterCallkitPlugin
      ios:
        pluginClass: FlutterCallkitPlugin
